# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c409da63fbe970c3e4c0235790cfc3a76ca20b51efd3b0089f0b7161dfa24de9d311ae40764bc9debdd208b1446d8361e75e01ed6f6c57992b6b2249597f0f7f

test:
  secret_key_base: f3bc2a06b9268594538e0cd9ede8b99645a7d17793fe70f77fef2341bb7d243aa7644f0ae17eec538f439c6fa6fca110bce15181c5a4200c3dc179d8928603d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
